# Generated by Django 4.2.5 on 2023-10-26 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_orders_orderid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
