# Generated by Django 4.2.5 on 2023-10-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_orders_orderid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(default='in process', max_length=20),
            preserve_default=False,
        ),
    ]
