# Generated by Django 4.2.5 on 2023-10-26 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_orders_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.CharField(max_length=10)),
                ('upload_image', models.FileField(default=None, max_length=250, null=True, upload_to='media/')),
            ],
        ),
    ]
