# Generated by Django 4.2.6 on 2023-10-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='type',
            field=models.CharField(default='all', max_length=20),
            preserve_default=False,
        ),
    ]
